### PR TITLE
CloudSdkServiceManager is null for non IDEA IDEs. Adds null safety.

### LINKED ISSUE #2138: NPE in GoLand when clicking submit feedback action
Likely occurs on other non IDEA IDEs too:

```
null
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.appengine.java.sdk.CloudSdkService.getInstance(CloudSdkService.java:28)
	at com.google.cloud.tools.intellij.CloudToolsFeedbackAction.getCloudSdkVersion(CloudToolsFeedbackAction.java:84)
	at com.google.cloud.tools.intellij.CloudToolsFeedbackAction.formatUrl(CloudToolsFeedbackAction.java:70)
	at com.google.cloud.tools.intellij.CloudToolsFeedbackAction.actionPerformed(CloudToolsFeedbackAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:301)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:104)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:291)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:528)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:48)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:548)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
```

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #2138

### CODE REVIEW

File: app-engine/java/src/com/google/cloud/tools/intellij/appengine/java/sdk/CloudSdkService.java [hunk 1]
```diff
@@ -25,7 +25,8 @@
 
   /** Shortcut for getting currently active implementation of {@link CloudSdkService}. */
   static CloudSdkService getInstance() {
-    return ServiceManager.getService(CloudSdkServiceManager.class).getCloudSdkService();
+    CloudSdkServiceManager service = ServiceManager.getService(CloudSdkServiceManager.class);
+    return service != null ? service.getCloudSdkService() : null;
```
Comment (ivanporty) [inline app-engine/java/src/com/google/cloud/tools/intellij/appengine/java/sdk/CloudSdkService.java]: Could we add a small comment on why this could be null? Not quite obvious since everything is there according to the code and configs.

Comment (etanshaul) [reply app-engine/java/src/com/google/cloud/tools/intellij/appengine/java/sdk/CloudSdkService.java]: sure
