### PR TITLE
Recheck application & region when manually typing in a cloud project

### LINKED ISSUE #1208: App Engine project selector region warning does't go away
To reproduce:

1) open up a flex project in IJ
2) open up the deployment configuration
3) select a project that is missing a region:
screen shot 2017-02-07 at 11 57 13 am
4) select a valid project that does have a region **by typing the project id**:
screen shot 2017-02-07 at 11 58 19 am

Notice the warning does not go away. If I were to manually select the project from the dropdown instead of typing it, it would disappear as expected.

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #1208

### CODE REVIEW

**Comment by etanshaul** [comment]
Previously, no event was fired when the user manually typed in a cloud project, causing any application / region errors to not go away.

This forces an event (on losing focus) which will then cause the region to be revalidated.

@aslo can you also ptal (since you wrote the pr dealing with app creation)?

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java [hunk 1]
```diff
@@ -391,6 +393,25 @@ public void showPopup(RelativePoint showTarget) {
...
+
+    getTextField().addFocusListener(new FocusListener() {
+      @Override
+      public void focusGained(FocusEvent e) {
+        // do nothing
+      }
+
+      @Override
+      public void focusLost(FocusEvent event) {
+        if (!event.isTemporary()) {
```
Comment (aslo) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java]: What does it mean for an event to be temporary?

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java [hunk 2]
```diff
@@ -391,6 +393,25 @@ public void showPopup(RelativePoint showTarget) {
...
+          onSelectionChanged(getCurrentModelItem());
```
Comment (aslo) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java]: This means that `onSelectionChanged` could be called with a null argument. Did you verify that this won't break anything if that happens?

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java [hunk 3]
```diff
@@ -391,6 +393,25 @@ public void showPopup(RelativePoint showTarget) {
     }
   }
 
+  @Override
+  public void addFocusListener() {
```
Comment (aslo) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java]: Small nit, but I'd argue that it might be cleaner to just call getTextField.addFocusListener(...) directly in this class's constructor rather than overriding this method. That way this class has control of how/when the listener is added.

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java]: yeah, totally.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java (hunk 1 above)
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java]: a lose focus event is permanent if it remains unfocused after everything is done. 

I noticed that this event was getting fired twice always: once with temporary=true and once with temporary=false. I did a little digging and saw that we can ignore the temporary once.

Comment (aslo) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java]: :+1:

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java (hunk 2 above)
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/ProjectSelector.java]: good catch!

**Comment by etanshaul** [comment]
@aslo - updated from your comments
