### PR TITLE
Null check and notification for null MavenProject

### LINKED ISSUE #2320: User reported NPE in addLibrariesToMavenModule
```
java.lang.NullPointerException at CloudLibraryDependencyWriter.addLibrariesToMavenModule : __NONE___
Stack trace:
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryDependencyWriter.addLibrariesToMavenModule(CloudLibraryDependencyWriter.java:105)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryDependencyWriter.addLibraries(CloudLibraryDependencyWriter.java:84)
	at com.google.cloud.tools.intellij.cloudapis.maven.MavenCloudApiUiExtension.onCloudLibrariesAddition(MavenCloudApiUiExtension.java:153)
	at com.google.cloud.tools.intellij.cloudapis.DefaultCloudApiUiPresenter.lambda$notifyCloudLibrariesAddition$4(DefaultCloudApiUiPresenter.java:121)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.google.cloud.tools.intellij.cloudapis.DefaultCloudApiUiPresenter.notifyCloudLibrariesAddition(DefaultCloudApiUiPresenter.java:121)
	at com.google.cloud.tools.intellij.cloudapis.AddCloudLibrariesAction.actionPerformed(AddCloudLibrariesAction.java:58)
```

plugin version 18.12.1
intellij version 2018.2.5

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #2320 

I was able to reproduce this by having a valid maven module (by importing a normal maven project) and then deleting the pom.xml. In this case, the module is still identified as a Maven module, but the `MavenProject` is null.

In this case, I am logging an error and showing the following notification to the user:
image

There is no good way to write a test for this given the way we are mocking maven modules (`MavenProject` is always non-null).

### CODE REVIEW

File: google-cloud-apis/java-apis/maven-apis/src/com/google/cloud/tools/intellij/cloudapis/maven/CloudLibraryDependencyWriter.java [hunk 1]
```diff
@@ -101,44 +103,55 @@ private static void addLibrariesToMavenModule(
...
-            libraries
-                .stream()
-                .map(CloudLibraryUtils::getFirstJavaClientMavenCoordinates)
-                .filter(Optional::isPresent)
-                .map(Optional::get)
-                .map(MavenUtils::toMavenId)
-                .collect(
-                    Collectors.partitioningBy(
-                        mavenId -> MavenUtils.isMavenIdInDependencyList(mavenId, dependencies)));
+    WriteCommandAction.writeCommandAction(project, DomUtil.getFile(model))
```
Comment (etanshaul) [inline google-cloud-apis/java-apis/maven-apis/src/com/google/cloud/tools/intellij/cloudapis/maven/CloudLibraryDependencyWriter.java]: this was a 1-to-1 refactoring to remove the call to deprecated API. the logic in the run lambda should be unchanged

File: google-cloud-apis/java-apis/maven-apis/src/com/google/cloud/tools/intellij/cloudapis/maven/CloudLibraryDependencyWriter.java [hunk 2]
```diff
@@ -101,44 +103,55 @@ private static void addLibrariesToMavenModule(
       @NotNull Set<CloudLibrary> libraries, @NotNull Module module, @Nullable String bomVersion) {
     Project project = module.getProject();
     MavenProject mavenProject = MavenProjectsManager.getInstance(project).findProject(module);
-    MavenDomProjectModel model =
-        MavenDomUtil.getMavenDomProjectModel(project, mavenProject.getFile());
+    MavenDomProjectModel model;
+    if (mavenProject != null) {
+      model = MavenDomUtil.getMavenDomProjectModel(project, mavenProject.getFile());
```
Comment (ivanporty) [inline google-cloud-apis/java-apis/maven-apis/src/com/google/cloud/tools/intellij/cloudapis/maven/CloudLibraryDependencyWriter.java]: I assume the result of this call never can be `null` ( I mean `getMavenDomProjectModel`)?

Comment (etanshaul) [reply google-cloud-apis/java-apis/maven-apis/src/com/google/cloud/tools/intellij/cloudapis/maven/CloudLibraryDependencyWriter.java]: it is actually `@Nullable`. I added a check for this too.
