### PR TITLE
Uses ImageIO to load the avatar image so errors during loading can be caught

### LINKED ISSUE #1377: Failed profile picture loads is sometimes causing errors in the IDE
this is on 2016.3.2.

my guess is that if `isGoodSize(icon)` is returning false, because the profile picture icon ends up having less than 1px width and/org height when it fails to load.

User error report:
```
Exception class name: java.lang.Throwable
Exception message: javax.swing.ImageIcon@29b7176
Stack trace:
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:135)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:105)
	at com.intellij.openapi.util.IconLoader.getDisabledIcon(IconLoader.java:294)
	at com.intellij.openapi.actionSystem.impl.ActionButton.updateIcon(ActionButton.java:255)
	at com.intellij.openapi.actionSystem.impl.ActionButton.presentationPropertyChanded(ActionButton.java:375)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at com.intellij.openapi.actionSystem.Presentation.setIcon(Presentation.java:217)
	at com.google.cloud.tools.intellij.login.ui.GoogleLoginActionButton.updateUi(GoogleLoginActionButton.java:69)
	at com.google.cloud.tools.intellij.login.IntellijGoogleLoginService$AndroidUiFacade$2.run(IntellijGoogleLoginService.java:523)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### PR DESCRIPTION
**Pull request by nkibler**
Fixes #1377.

**Cause:** The previous method of image loading (Toolkit.prepareImage()) doesn't easily allow for catching errors during the process of loading the image. Previously, the returned image reference was non-null, but it had no pixel data behind it. When passed down to the IconLoader, it assumes that if it's non-null, it actually has data behind it so it logs an error.

**Solution:** Use the superior ImageIO utility to load the image. This allows catching an IOException when there's an error resolving the URL, at which point we can return a null reference. Also, if the URL resolves but the encoded data is somehow misformatted, a null reference is returned. A bonus of this method is that it uses an internal caching mechanism.

**Observed Changes:** If the avatar image fails to load, the default avatar icon is used and no error log is printed.

### CODE REVIEW

File: google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginUtils.java [hunk 1]
```diff
@@ -53,8 +53,7 @@
    * @param pictureCallback the user image will be set on this callback
    */
   @SuppressWarnings("FutureReturnValueIgnored")
-  public static void provideUserPicture(Userinfoplus userInfo,
-      final IUserPropertyCallback<Image> pictureCallback) {
+  public static void provideUserPicture(Userinfoplus userInfo, Consumer<Image> pictureCallback) {
```
Comment (patflynn) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginUtils.java]: as an aside, we shouldn't be doing IO in a static context. (not your problem and don't fix it here)

Comment (nkibler) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginUtils.java]: Yeah I agree, a lot of this would change if we decide to lean on the google-auth-library.
