### PR TITLE
Few cosmetic enhancements and fixes in ProjectSelector.

### LINKED ISSUE #1791: Project selector should select account after sign in
1) start logged out of all google accounts
2) load up the new project selector and click to open a dialog
3) sign into your account

-> I would have expected the account I just signed into to be selected now. Instead, no account is selected  (it _is_ in the dropdown, I just need to manually choose it):

image

image

### PR DESCRIPTION
**Pull request by ivanporty**
Fixes #1791, #1792, #1794.
Also updates project list to render all matching cases bold regardless of case.

### CODE REVIEW

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/project/ProjectSelectionDialog.java [hunk 1]
```diff
@@ -215,7 +217,12 @@ public void onFailure(Throwable throwable) {
   private void refreshDialog() {
     CredentialedUser currentUser = (CredentialedUser) accountComboBox.getSelectedItem();
     loadAllProjects();
-    accountComboBox.setSelectedItem(currentUser);
+    if (currentUser != null) {
+      accountComboBox.setSelectedItem(currentUser);
+    } else {
+      // no selection before, select active user by default.
```
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/project/ProjectSelectionDialog.java]: Did you confirm that the most recently logged in user will be the active user?

The behavior I think we are after is that the _most recently logged in user_ is the one selected in the dropdown, regardless of if its the default user or not.

**Comment by etanshaul** [comment]
I may be crazy, but where in this PR did you fix #1792 (removing the old loader)?

**Comment by ivanporty** [comment]
Here, this line has been removed in the dialog code: ((JBTable) projectListTable).setPaintBusy(loading);
this was the call to set table as 'loading'

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/project/ProjectSelectionDialog.java (hunk 1 above)
Comment (ivanporty) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/project/ProjectSelectionDialog.java]: So, when we reload, we take the currently selected user, and after reload, set it back as selected so the state is preserved. If nothing was selected (no signed in users first), we check for null and set user to active - which I think is the most recently logged in user.

Comment (etanshaul) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/project/ProjectSelectionDialog.java]: Yeah thats what I wanted to be sure of - that the most recently logged in user will always be selected (even if I am already logged in to one or more accounts). I think, that be adding a new account I'd want that new account selected on successful login (even if there are other accounts already logged in).

Comment (ivanporty) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/project/ProjectSelectionDialog.java]: Got it, updated - so manual refresh now keeps the selection, but if we change accounts, i.e. add new active one, dialog will switch to new active one and load its project list.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/project/ProjectSelectionDialog.java [hunk 2]
```diff
@@ -211,11 +217,21 @@ public void onFailure(Throwable throwable) {
...
 
-  /** Preserves currently selected account and refreshes accounts and project lists. */
-  private void refreshDialog() {
+  /**
+   * Preserves currently selected account if requested and refreshes accounts and project lists.
+   *
+   * @param keepPreviousSelection true to keep current user selected after refresh. false to select
+   *     active user instead.
+   */
+  private void refreshDialog(boolean keepPreviousSelection) {
```
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/project/ProjectSelectionDialog.java]: would it be possible to directly pass in the user to select rather than having a flag like this?

Comment (ivanporty) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/project/ProjectSelectionDialog.java]: good idea, let me rework it that way,
