### PR TITLE
Check if Cloud SDK was declared on local dev server run config.

### LINKED ISSUE #1028: User reported error 'cloud sdk not found'
Seems odd that this error would show up as an IDE error vs a validation issue.

Exception class name: com.google.cloud.tools.appengine.api.AppEngineException: Google Cloud SDK path was not provided and could not be found in any known install locations.
Exception message: Google Cloud SDK path was not provided and could not be found in any known install locations.
Stack trace:
com.google.cloud.tools.appengine.api.AppEngineException: Google Cloud SDK path was not provided and could not be found in any known install locations.
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk$Builder.discoverSdkPath(CloudSdk.java:543)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk$Builder.build(CloudSdk.java:485)
	at com.google.cloud.tools.intellij.appengine.server.instance.AppEngineServerModel.checkConfiguration(AppEngineServerModel.java:166)
	at com.intellij.javaee.run.configuration.CommonStrategy.checkConfiguration(CommonStrategy.java:325)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.checkSettings(RunnerAndConfigurationSettingsImpl.java:423)
	at com.intellij.execution.impl.RunManagerImpl.canRunConfiguration(RunManagerImpl.java:535)
	at com.intellij.execution.impl.RunManagerImpl.canRunConfiguration(RunManagerImpl.java:530)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:71)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:117)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:67)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:509)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

SDK version:
Release: 2016.2.4
app.name.version	
IntelliJ IDEA
app.version.major	
2016
app.version.minor	
2.4
java.version	
1.8.0_112-release
JetBrains s.r.o
os.name	
Windows 10
plugin.version	
16.10.4

### PR DESCRIPTION
**Pull request by joaoandremartins**
Fixes #1028

### CODE REVIEW

File: google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java [hunk 1]
```diff
@@ -162,14 +162,20 @@ public void checkConfiguration() throws RuntimeConfigurationException {
           "App Engine facet not found in '" + artifact.getName() + "' artifact");
     }
 
+    if (CloudSdkService.getInstance().getSdkHomePath() == null) {
+      throw new RuntimeConfigurationError(
```
Comment (aslo) [inline google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java]: Why a `RuntimeConfigurationError` and not a `RuntimeConfigurationWarning`, as above?

**Comment by etanshaul** [comment]
lgtm

File: google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java (hunk 1 above)
Comment (joaoandremartins) [inline google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java]: Good question! Because without Cloud SDK, we can't have dev_appserver and essentially can't run the run config.

Another good question would be why the above is Warning only. I'm guessing it's because it's still possible to locally run an app without the App Engine facet (which we're currently not using for anything AFAIK).

Comment (aslo) [inline google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java]: Makes sense.

Comment (etanshaul) [inline google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java]: I'd be curious to know if you can locally run without the facet. I think you can, but the existence of the dev server local run config I think is dependent AE framework support (which adds the AE facet) - but this doesn't mean that removing the facet would cause the local run not to work.

Comment (joaoandremartins) [inline google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java]: Yeah, I just removed the facet and the projects runs great. Which makes me wonder: should we actually remove that warning? Or are we going to have any use for a facet in local runs, in the future?

If dev_appserver doesn't include the SDK libraries by default, we could probably add them to the facet? Need to check this, though.

Comment (joaoandremartins) [inline google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java]: Actually, libs are already in the facet, so I just need to check if dev_appserver automatically gets them.

Comment (joaoandremartins) [inline google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineServerModel.java]: dev_appserver gets whatever was staged, so we indeed have a bit of a dependency on the facet to grab dependencies, if even only for non-Maven projects/artifacts.
