### PR TITLE
Workaround for hasErrors() method not present in 2017.3 version.

### LINKED ISSUE #2073: DialogWrapper#hasErrors was introduced in 2018.1. fails in 2017.3
ServiceAccountKeyUltimateDisplayDialog calls this method, breaking the previous-version CI

### PR DESCRIPTION
**Pull request by ivanporty**
Fixes #2073.

### CODE REVIEW

File: gradle.properties [hunk 1]
```diff
@@ -15,7 +15,7 @@
 #
 
 ideaEdition = IU
-ideaVersion = 2018.1
+ideaVersion = 2017.3
```
Comment (ivanporty) [inline gradle.properties]: just for testing, to be reverted before merge.

File: google-cloud-tools-plugin/app-engine/java/ultimate/src/com/google/cloud/tools/intellij/appengine/java/ultimate/cloudapis/ServiceAccountKeyUltimateDisplayDialog.java [hunk 2]
```diff
@@ -153,19 +153,24 @@ private void createUIComponents() {
   }
 
   @VisibleForTesting
-  public void addEnvironmentVariablesToConfiguration(
+  public boolean addEnvironmentVariablesToConfiguration(
```
Comment (etanshaul) [inline google-cloud-tools-plugin/app-engine/java/ultimate/src/com/google/cloud/tools/intellij/appengine/java/ultimate/cloudapis/ServiceAccountKeyUltimateDisplayDialog.java]: mind adding a javadoc for this?
