### PR TITLE
Fixes project selector reloading issues with applied filters

### LINKED ISSUE #1709: Same Cloud Project displays multiple times in project selector
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version: 17.GCS-RC2
- Google Cloud SDK version _(run `gcloud version` on the command line)_: 176.0.0
- OS: Linux

**What did you do?**
I wanted to select a different GCS bucket for my app. When I clicked the drop-down menu, I saw the same project listed 3 times.

**What did you expect to see?**
I expected to see the project that I selected and then a list of the available GCP projects.
**What did you see instead?**

(screenshots are helpful)

(https://user-images.githubusercontent.com/11820506/31950228-26e829b8-b8a9-11e7-99d5-9ed18acd8686.png)

### PR DESCRIPTION
**Pull request by nkibler**
Fixes #1709.

The problem is that the filtering logic overrides the `getChildAt()` and `getChildCount()` methods in the `GoogleUserModelItem`. While it's important to do this for rendering purposes (so it only renders filtered children), when removing children, we never want to restrict the removal to just the filtered children. This PR adds overrides to the `remove()` and `removeAllChildren()` methods to not rely on the `getChildAt()` or `getChildCount()` methods and instead use the raw `children` vector directly.

### CODE REVIEW

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/GoogleUserModelItem.java [hunk 1]
```diff
@@ -225,6 +230,35 @@ public int getChildCount() {
...
+  @Override
+  public void removeAllChildren() {
+    if (children == null) {
+      return;
+    }
+
+    // This is different from the default implementation because it uses the raw children vector
+    // instead of relying on the getChildCount() method, which has been modified to only return
+    // the number of filtered children.
+    for (int i = children.size() - 1; i >= 0; i--) {
```
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/GoogleUserModelItem.java]: nit: `forEach` instead?

**Comment by etanshaul** [comment]
lgtm. but could you point out the part relevant to the original bug (that the project was being displayed multiple times)?

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/GoogleUserModelItem.java (hunk 1 above)
Comment (nkibler) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/GoogleUserModelItem.java]: It would probably throw a `ConcurrentModificationException` since the loop modifies the underlying `children` vector. Also, I believe the point of reverse-iterating through the children is to prevent any shifting of positions that the `Vector` might do if I removed from beginning to end.

**Comment by nkibler** [comment]
The relevant part is the override to `removeAllChildren()`. Here's the (unmodified) line that was causing issues: https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/d5b0ef5a0bf9264749249ffe63bf6b3e8c03be96/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/GoogleUserModelItem.java#L203

Before this change, the `removeAllChildren()` method would use a count and `getChildAt()` method that depended on the filtered children. After this change, this line to `removeAllChildren()` before we add the new ones on synchronization will actually remove all the children, regardless of the applied filter.

**Comment by etanshaul** [comment]
makes sense. was there anything special you had to do to trigger the bug? Like have a filter then close and reopen the panel, or something like that? Just asking cause I wasn't able to trigger it.

**Comment by nkibler** [comment]
Yeah, my repro steps were:

1. Open the project selector by any means.
2. Type text to apply a filter.
3. Press the _Synchronize_ button.
4. Modify the text to actually re-apply the filter after the synchronization and notice the duplicated nodes.

That last point was also fixed; the filter is now re-applied to the new nodes after synchronizing.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/GoogleUserModelItem.java [hunk 2]
```diff
@@ -203,6 +206,8 @@ private void loadUserProjects() {
               GoogleUserModelItem.this.add(item);
             }
 
+            // Re-applies the filter to the new child nodes.
+            setFilter(filter);
```
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/GoogleUserModelItem.java]: should we check for null here? I know that ResourceProjectModelItem takes a nullable filter, but maybe this could same some cycles?

Comment (nkibler) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/GoogleUserModelItem.java]: Done.
