### PR TITLE
Deserialize maven build deployment source types

### LINKED ISSUE #989: Maven deployment sources are not properly deserialized
Steps:

1) Open a project with a maven build deployment source
2) Deploy it -> notice that the deployment proceeds
3) Close the project, reopen it
4) Deploy again -> fails with the following:

[ 122559]  ERROR - pplication.impl.LaterInvocator - Invalid deployment source selected for deployment 
java.lang.RuntimeException: Invalid deployment source selected for deployment

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #989 

@joaoandremartins @patflynn @aslo

### CODE REVIEW

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/CloudSdkAppEngineHelper.java [hunk 1]
```diff
@@ -43,6 +43,7 @@
 import com.intellij.openapi.util.io.FileUtil;
 import com.intellij.openapi.vcs.impl.CancellableRunnable;
 import com.intellij.remoteServer.configuration.deployment.DeploymentSource;
+import com.intellij.remoteServer.configuration.deployment.ModuleDeploymentSource;
```
Comment (joaoandremartins) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/CloudSdkAppEngineHelper.java]: Is this needed?

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSourceType.java [hunk 2]
```diff
@@ -67,6 +82,43 @@ protected BeforeRunTask createBuildTask(@NotNull Module module) {
...
+
+      if (module.isPresent() && environment != null) {
+        return new MavenBuildDeploymentSource(
+            ModulePointerManager.getInstance(project).create(module.get()),
+            project,
+            AppEngineEnvironment.valueOf(environment));
+      }
+    }
+
+    return new MavenBuildDeploymentSource(
```
Comment (joaoandremartins) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSourceType.java]: Out of curiosity, when does it happen that we don't know the deployment source environment? Is `settings` expected to be null?

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java [hunk 3]
```diff
@@ -40,7 +44,15 @@
     implements AppEngineDeployable {
 
   private final Project project;
-  private final AppEngineEnvironment environment;
+  private AppEngineEnvironment environment;
```
Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java]: I thought we didn't want to serialize environment at all because of that previous freshness issue.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSourceType.java (hunk 2 above)
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSourceType.java]: good question - see my last commit. I refactored this. Hopefully it fixes your concern.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java (hunk 3 above)
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java]: oh....good point! Let me update this.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java [hunk 4]
```diff
@@ -86,6 +98,14 @@ public File getFile() {
         new File(mavenProject.getBuildDirectory()).getPath() + File.separator
             + mavenProject.getFinalName();
 
+    // The environment will be null for newly deserialized deployment sources to ensure freshness.
+    // In this case, we need to reload the environment.
+    if (environment == null) {
+      environment = AppEngineProjectService.getInstance().getModuleAppEngineEnvironment(
```
Comment (joaoandremartins) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java]: So, IIUC, we will always be recalculating the environment for maven build sources, which might involve an expensive disk query. I'm wondering if there is a way to save some of this work, e.g., by caching the environment in the persisted settings as we appeared to be doing before. I wouldn't think this is critical, though.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/BuildDeploymentSourceType.java [hunk 5]
```diff
@@ -41,7 +41,12 @@
  * for specific build-systems should extend this providing the build-system specific
  * implementations.
  */
-public abstract class BuildDeploymentSourceType extends ModuleDeploymentSourceType {
+public abstract class BuildDeploymentSourceType
+    extends DeploymentSourceType<ModuleDeploymentSource> {
```
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/BuildDeploymentSourceType.java]: In case anyone was wondering why I changed it to extend DeploymentSourceType instead of ModuleDeploymentSourceType: in order to deserialize our maven sources, we need to be able to set an ID (this is how the platform locates the object to load). ModuleDeploymentSourceType does not expose a constructor to set this id (and wasn't adding any useful functionality on top of DeploymentSourceType.

**Comment by etanshaul** [comment]
@patflynn updated to not deserialize based on environment
