### PR TITLE
Reset module config

### LINKED ISSUE #1283: Removing the Flexible facet from the Module Settings dialog should hide module selector and Module Settings button
As is, if the facet is removed, the run config can't be persisted without the user specifying an app.yaml.

However, if the button is clicked, an exception is thrown.

But it'd be cooler if we hid the Module Settings dialog and the module selector, kinda like what happens when a run config is created without Flex facet in any module.

screen shot 2017-03-03 at 10 13 50 am

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #1283

### CODE REVIEW

File: google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditorTest.java [hunk 1]
```diff
@@ -389,13 +389,12 @@ public void testDockerfileOverride() {
     assertEquals("an override", editor.getDockerfileTextField().getText());
   }
 
-  public void testDockerfileStartsDisabledAndWithModuleSetting() {
+  public void testDockerfileStartsDisabled() {
```
Comment (etanshaul) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditorTest.java]: I need to verify this. Specifically checking to see if this unit test was valid and why my changes changed the behavior. @joaoandremartins if anything jumps out at you let me know since you wrote this originally.

File: google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditorTest.java [hunk 2]
```diff
@@ -389,13 +389,12 @@ public void testDockerfileOverride() {
...
     ApplicationManager.getApplication().runWriteAction(
         () -> ModuleManager.getInstance(getProject()).disposeModule(javaModule));
     editor = new AppEngineFlexibleDeploymentEditor(getProject(), deploymentSource);
     assertEquals(1, editor.getModulesWithFlexFacetComboBox().getItemCount());
     assertFalse(editor.getDockerfileTextField().isEnabled());
-    assertEquals(dockerfile.getPath(), editor.getDockerfileTextField().getText());
```
Comment (etanshaul) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditorTest.java]: @joaoandremartins I removed this because with my changes, the text field was empty string so this assertion was failing.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditor.java [hunk 3]
```diff
@@ -106,12 +108,12 @@
   private JButton moduleSettingsButton;
   private JCheckBox hiddenValidationTrigger;
   private JLabel noSupportedModulesWarning;
-  private DeploymentSource deploymentSource;
 
   private static final boolean PROMOTE_DEFAULT = false;
   private static final boolean STOP_PREVIOUS_VERSION_DEFAULT = false;
 
   public AppEngineFlexibleDeploymentEditor(Project project, AppEngineDeployable deploymentSource) {
+    this.project = project;
```
Comment (joaoandremartins) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditor.java]: I'd rather we don't set project as a member of the class, if not strictly necessary. Pass it to the one method that requires it from the constructor, instead.

File: google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditorTest.java (hunk 1 above)
Comment (joaoandremartins) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditorTest.java]: Maybe the order counts.
I'm wondering if when the combo box model is changed, toggleDockerfileSection() is triggered by the item listener?

**Comment by etanshaul** [comment]
ptal
