### PR TITLE
Fix NPE with null MavenDomProjectModel

### LINKED ISSUE #1980: User reported NPE in CloudLibraryProjectState
Stack trace:
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.apis.CloudLibraryProjectState.lambda$getModuleDependencies$1(CloudLibraryProjectState.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.google.cloud.tools.intellij.apis.CloudLibraryProjectState.getModuleDependencies(CloudLibraryProjectState.java:131)
	at com.google.cloud.tools.intellij.apis.CloudLibraryProjectState.loadManagedLibraries(CloudLibraryProjectState.java:104)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #1980 

The model could be null if its a maven project, but the pom is invalid in some way. In this case, we just return no dependencies.

Updated the method to not return null lists, and added a unit test to cover the bug.

### CODE REVIEW

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/apis/CloudLibraryProjectState.java [hunk 1]
```diff
@@ -134,7 +135,9 @@ void syncManagedProjectLibraries() {
                   MavenDomProjectModel model =
                       MavenDomUtil.getMavenDomProjectModel(project, mavenProject.getFile());
 
-                  return model.getDependencies().getDependencies();
+                  return model != null
+                      ? model.getDependencies().getDependencies()
```
Comment (ivanporty) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/apis/CloudLibraryProjectState.java]: will `model.getDependencies()` always be non-null as well?

Comment (etanshaul) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/apis/CloudLibraryProjectState.java]: it is @NotNull. But I am still checking in the caller that the return of this method != null.

Comment (etanshaul) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/apis/CloudLibraryProjectState.java]: oh nm. yes model.getDependencies is @NotNull. Thought you were asking about getDependencies#getDependencies at first
