### PR TITLE
Fix for vanishing local dev run config

### LINKED ISSUE #1147: Local dev server run config vanishes
To reproduce:

1) create a new AE standard project. notice the local dev run config gets created
2) close the project, then reopen it

Notice the run config is gone.

### PR DESCRIPTION
**Pull request by etanshaul**
Fixes #1147 

The problem was that the getName method in the ConfigurationFactory was not overriden. This is needed on project re-open so that the previously created one can be restored. 

Also updating the overriden methods to delegate to the already existing ConfigurationFactory's methods.

### CODE REVIEW

File: google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/run/AppEngineServerConfigurationType.java [hunk 1]
```diff
@@ -72,12 +72,19 @@ public Icon getIcon() {
...
+          @Override
+          public String getName() {
+            return configurationFactory.getName();
+          }
+
           @NotNull
           @Override
           public RunConfiguration createTemplateConfiguration(@NotNull Project project) {
-            return createJ2EEConfigurationTemplate(this, project, true /*isLocal*/);
+            return configurationFactory.createTemplateConfiguration(project);
```
Comment (etanshaul) [inline google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/run/AppEngineServerConfigurationType.java]: yes, ultimately it does the same thing. I think its better code to do the delegation like I updated it do instead of recreating it.
