### PR TITLE
Fix flex environment check NPE

### LINKED ISSUE #1923: User reported NPE in AppEngineFlexibleSupportProvider
plugin version 18.2.1

Cluster
java.lang.NullPointerException at AppEngineFlexibleSupportProvider.lambda$hasFlexibleDeploymentConfiguration$3 : null
Description
null
Stack trace:
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.appengine.facet.flexible.AppEngineFlexibleSupportProvider.lambda$hasFlexibleDeploymentConfiguration$3(AppEngineFlexibleSupportProvider.java:164)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1353)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #1923

### CODE REVIEW

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/facet/flexible/AppEngineFlexibleSupportProvider.java [hunk 1]
```diff
@@ -162,8 +163,11 @@ private static boolean hasFlexibleDeploymentConfiguration(List<RunConfiguration>
         .map(runConfig -> ((DeployToServerRunConfiguration) runConfig).getDeploymentConfiguration())
         .filter(deployConfig -> deployConfig instanceof AppEngineDeploymentConfiguration)
         .anyMatch(
-            deployConfig ->
-                ((AppEngineDeploymentConfiguration) deployConfig).getEnvironment().isFlexible());
+            deployConfig -> {
+              AppEngineEnvironment environment =
+                  ((AppEngineDeploymentConfiguration) deployConfig).getEnvironment();
+              return environment != null && environment.isFlexible();
```
Comment (ivanporty) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/facet/flexible/AppEngineFlexibleSupportProvider.java]: So this is an expected case when environment could be `null`?

Comment (etanshaul) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/facet/flexible/AppEngineFlexibleSupportProvider.java]: I'm not 100% sure how it was null in the first place. My reasoning is that it is harmless to silently skip this case since, if you look at what this method is used for, it will just go ahead and create a working deployment run configuration. wdyt?
