### PR TITLE
Fixes the addition of the file extension on Maven artifacts

### LINKED ISSUE #1220: Deployment source not found
I am encountering an issue deploying my application to App Engine using IntelliJ (Google Cloud Tools Plugin 16.11.16)

Every time I deploy I receive the following message:
Deploying '[2017-02-08 12:22:11] Maven build: TestApp. Project: my-server. Version: auto'...
Failed to deploy '[2017-02-08 12:22:11] Maven build: TestApp. Project: my-server. Version: auto': Deployment source not found: /Users/../TestApp/target/Test-App-1.0-SNAPSHOT.

Can you please advise?

### PR DESCRIPTION
**Pull request by nkibler**
Fixes #1220.

The problem (as described in #1220) is that https://github.com/GoogleCloudPlatform/google-cloud-intellij/commit/5020c8c6b91925daa3c58cd4f05e62231d6147d2 incorrectly changed the behavior to only append the extension of the built Maven artifact when the environment was `null` and needed deserialized. For `MavenBuildDeploymentSources` that already had their environment populated, the extension was not appended (for flexible deployments that count on this file extension).

### CODE REVIEW

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java [hunk 1]
```diff
@@ -130,17 +122,12 @@ public File getFile() {
...
-            if (env.isFlexible()) {
-              targetBuild.append(".");
-              targetBuild.append(mavenProject.getPackaging());
-            }
-          });
+      projectService.getModuleAppEngineEnvironment(getModule()).ifPresent(env -> environment = env);
+    }
+
+    if (environment != null && environment.isFlexible()) {
+      targetBuild.append(".");
```
Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java]: let's verify that standard deployment of maven artifacts is working.

Comment (nkibler) [reply google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/MavenBuildDeploymentSource.java]: I just checked and it does work for App Engine standard deployments. (Offline I mentioned that it doesn't work, but that was because my Maven project was not configured to build a WAR, so the exploded folder wasn't created.)

**Comment by patflynn** [comment]
great. feel free to merge when ready,
