### PR TITLE
Fixes user icon size at higher DPI scales

### LINKED ISSUE #1391: Google Account Login on HIDPI screen to small
When on a HiDPI screen on fedora (25) the google avatar is shown too small (should be 2x), see image:

image

### PR DESCRIPTION
**Pull request by nkibler**
Fixes #1391.

Can anyone verify this on a HiDPI monitor? I can't locally verify but judging by the code in the `JBUI.pixScale()` method, it should fix the issue.

**Problem:** The user's image is scaled manually to 16x16, regardless of the calculated pixel scale (which takes into account user settings and system settings).

**Solution:** Use the provided `JBUI.pixScale()` method to determine the appropriate size of this icon before scaling it down.

### CODE REVIEW

**Comment by patflynn** [comment]
I can do this on my laptop tomorrow :)

**Comment by etanshaul** [comment]
interestingly im not able to reproduce the original problem on my macbook (posted this accidentally on the issue before).

Still playing around with dpi settings to see if I can.

File: google-account-plugin/src/com/google/cloud/tools/intellij/login/ui/GoogleLoginAction.java [hunk 1]
```diff
@@ -69,15 +65,14 @@ public void update(AnActionEvent e) {
       if (image == null) {
         presentation.setIcon(GoogleLoginIcons.DEFAULT_USER_AVATAR);
```
Comment (patflynn) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/ui/GoogleLoginAction.java]: does Google provide how and low res avatar images we can use?

Comment (nkibler) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/ui/GoogleLoginAction.java]: Oh you mean loading over HTTP instead of local assets? We could do that if you want.

Comment (patflynn) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/ui/GoogleLoginAction.java]: I guess I'm just asking of we can get high dpi versions of the resources instead of scaling.

Comment (nkibler) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/ui/GoogleLoginAction.java]: For the default icons, we have 16x16 and 32x32 already, the latter is for retina displays. The scaling we're doing is on the icon we pull from their profile, which I believe is coming in at 96x96 to support the account popup size. We just resize for the smaller icon.

Comment (patflynn) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/ui/GoogleLoginAction.java]: ah ok that makes sense.

**Comment by patflynn** [comment]
@etanshaul I can actually reproduce this on my work machine. Unfortunately can't get the local run version of intellij to respect my scaling settings.

**Comment by patflynn** [comment]
@nkibler built this branch locally and installed from disk into IJ on High DPI screen that was exhibiting this issue.  Verified the fix works.
