### PR TITLE
Fix plugin exceptions with EAP

### LINKED ISSUE #2124: User reported NPE on EAP
2018.2 EAP
plugin version 18.4.1

```
java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at com.google.cloud.tools.intellij.appengine.java.cloud.AppEngineDeploymentConfigurationPanel.$$$setupUI$$$(AppEngineDeploymentConfigurationPanel.java)
	at com.google.cloud.tools.intellij.appengine.java.cloud.AppEngineDeploymentConfigurationPanel.<init>(AppEngineDeploymentConfigurationPanel.java:64)
	at com.google.cloud.tools.intellij.appengine.java.cloud.standard.AppEngineStandardDeploymentEditor.createUIComponents(AppEngineStandardDeploymentEditor.java:95)
	at com.google.cloud.tools.intellij.appengine.java.cloud.standard.AppEngineStandardDeploymentEditor.$$$setupUI$$$(AppEngineStandardDeploymentEditor.java)
	at com.google.cloud.tools.intellij.appengine.java.cloud.standard.AppEngineStandardDeploymentEditor.<init>(AppEngineStandardDeploymentEditor.java:47)
	at com.google.cloud.tools.intellij.appengine.java.cloud.AppEngineDeploymentConfigurator.createEditor(AppEngineDeploymentConfigurator.java:83)
	at com.intellij.remoteServer.impl.configuration.deployment.DeployToServerSettingsEditor.updateDeploymentSettingsEditor(DeployToServerSettingsEditor.java:97)
	at com.intellij.remoteServer.impl.configuration.deployment.DeployToServerSettingsEditor$AnySource.lambda$new$0(DeployToServerSettingsEditor.java:188)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
```

### PR DESCRIPTION
**Pull request by ivanporty**
Fixes #2124.

Changes to make plugin work with EAP:
* Replaced obsolete icons with pre-loaded icons from 'AllIcons' or other icons available in both builds
* Refactored unit test for cloud breakpoints to avoid mocking method made final in new release (`getXBreakpoint`)
* Refactored CloudApiManagementConfirmationDialog to avoid instrumentation error with roles field being null
* Changed `GoogleCloudApiDetailsPanel.form` to use default IDEA layout manager (`GridLayoutManager`) instead of Form Layout which seems to be removed from the next version.

### CODE REVIEW

**Comment by etanshaul** [comment]
the layout manager change for the API panel didn't change the look and feel at all?

**Comment by ivanporty** [comment]
Those layout are really similar, I did changed a few tricks but the resulting layout is the same. Let me attach the screenshot.

File: google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/AddCloudLibrariesDialog.java [hunk 1]
```diff
@@ -113,7 +112,7 @@ protected void doOKAction() {
       CloudApiManagementConfirmationDialog managementDialog =
           new CloudApiManagementConfirmationDialog(
               getSelectedModule(), cloudProject, apisToEnable, apisNotEnabled, roles);
-      DialogManager.show(managementDialog);
+      managementDialog.show();
```
Comment (etanshaul) [inline google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/AddCloudLibrariesDialog.java]: just curious - why was this one needed?

**Comment by etanshaul** [comment]
sounds good. I'll take your word for it if it looks the same. Thanks

File: google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/AddCloudLibrariesDialog.java (hunk 1 above)
Comment (ivanporty) [reply google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/AddCloudLibrariesDialog.java]: Not the best idea to use DialogManager from a very specific package - it's from `git4idea`, there are not `DialogManager` in the core platform, you can just show the dialog itself. Cleaned up as I noticed this wierd import.

File: google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/CloudApiManagementConfirmationDialog.java [hunk 2]
```diff
@@ -123,6 +126,9 @@
             GoogleCloudApisMessageBundle.message(
                 "cloud.apis.management.dialog.serviceaccount.header")));
 
+    infoLabel.setIcon(General.Information);
```
Comment (etanshaul) [inline google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/CloudApiManagementConfirmationDialog.java]: just to confirm - looks like you are setting the icon in code now (instead of I assume in the form like before). Is that something needed for the fix?

File: google-cloud-apis/testSrc/com/google/cloud/tools/intellij/cloudapis/GoogleCloudApiSelectorPanelTest.java [hunk 3]
```diff
@@ -139,6 +140,10 @@
   @Before
   public void setUp() {
     moduleBuilder = MavenTestUtils.getInstance().initMavenModuleBuilder(testFixture.getProject());
+
+    // TODO: remove after Batik fix is available in IDEA itself - happens when SVG icons are used.
```
[the remark this answers is not in the document]
Comment (ivanporty) [reply google-cloud-apis/testSrc/com/google/cloud/tools/intellij/cloudapis/GoogleCloudApiSelectorPanelTest.java]: There are no bugs or PRs assigned to this - just master commit.

[the remark this answers is not in the document]
Comment (etanshaul) [reply google-cloud-apis/testSrc/com/google/cloud/tools/intellij/cloudapis/GoogleCloudApiSelectorPanelTest.java]: ah. maybe the commit hash then?

File: google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/CloudApiManagementConfirmationDialog.java (hunk 2 above)
Comment (ivanporty) [reply google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/CloudApiManagementConfirmationDialog.java]: yeah, it's impossible to set icon directly as the form editor supports PNG/GIF or other pixel formats, and they now use SVG which must be loaded first.

File: google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/AddCloudLibrariesDialog.java (hunk 1 above)
Comment (etanshaul) [reply google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/AddCloudLibrariesDialog.java]: I noticed that it came from git4idea. I thought something was up with my Gradle sync. sounds good

File: google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/CloudApiManagementConfirmationDialog.java (hunk 2 above)
Comment (etanshaul) [reply google-cloud-apis/src/com/google/cloud/tools/intellij/cloudapis/CloudApiManagementConfirmationDialog.java]: got it. thanks

**Comment by ivanporty** [comment]
libs-new-layout1
libs-new-layout2

File: google-cloud-apis/testSrc/com/google/cloud/tools/intellij/cloudapis/GoogleCloudApiSelectorPanelTest.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (ivanporty) [reply google-cloud-apis/testSrc/com/google/cloud/tools/intellij/cloudapis/GoogleCloudApiSelectorPanelTest.java]: added
