### PR TITLE
Test errors "Too many projects leaks"

### LINKED ISSUE #1459: Flaky Tests due to a detected Project 'leak'
Our CI builds are frequently red due to this issue:
```

com.google.cloud.tools.intellij.debugger.CloudExecutionStackTest > testGetTopFrame_nullFramesReturnsNull SKIPPED

com.google.cloud.tools.intellij.debugger.CloudExecutionStackTest > testGetTopFrame_nonNull SKIPPED

com.google.cloud.tools.intellij.debugger.ui.CloudAttachDialogTest > testDebuggableModuleSelected FAILED
    junit.framework.AssertionFailedError: Too many projects leaked: 
    Project (Disposed) testDockerfileStartsDisabledAndWithModuleSettingcom.google.cloud.tools.intellij.appengine.cloud.flexible.AppEngineFlexibleDeploymentEditorTest.testDockerfileStartsDisabledAndWithModuleSetting
    Project (Disposed) testSuggestion_nullPathcom.google.cloud.tools.intellij.appengine.cloud.flexible.SelectConfigDestinationFolderDialogTest.testSuggestion_nullPath
    Project (Disposed) testRemoveConsolePanecom.google.cloud.tools.intellij.debugger.CloudDebugProcessTest.testRemoveConsolePane
    Project (Disposed) testSuggestioncom.google.cloud.tools.intellij.appengine.cloud.flexible.SelectConfigDestinationFolderDialogTest.testSuggestion
    Project (Disposed) testSuggestion_noParentcom.google.cloud.tools.intellij.appengine.cloud.flexible.SelectConfigDestinationFolderDialogTest.testSuggestion_noParent

    Please see '/Volumes/BuildData/tmpfs/tmp/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2017.1/7f417b38c7a1613648ac9d9b266a2fb936d60407/ideaIU-2017.1/leakedProjects.hprof.zip' for a memory dump
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.TestCase.fail(TestCase.java:227)
        at com.intellij.testFramework.PlatformTestCase.createProject(PlatformTestCase.java:293)
        at com.intellij.testFramework.PlatformTestCase.createProject(PlatformTestCase.java:254)
        at com.intellij.testFramework.PlatformTestCase.doCreateProject(PlatformTestCase.java:249)
        at com.intellij.testFramework.PlatformTestCase.setUpProject(PlatformTestCase.java:234)
        at com.intellij.testFramework.PlatformTestCase.setUp(PlatformTestCase.java:202)
        at com.google.cloud.tools.intellij.debugger.ui.CloudAttachDialogTest.setUp(CloudAttachDialogTest.java:62)

357 tests completed, 1 failed, 2 skipped
:google-cloud-tools-plugin:test FAILED

```

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #1459 

attempting to find the problem

### CODE REVIEW

**Comment by etanshaul** [comment]
ok so looks like those 2 tests are the main offenders (doesn't mean there arent others, just that these are causing the IJ project leak detection to go off). I'll look into fixing them so I can unignore them.

**Comment by etanshaul** [comment]
@patflynn ptal. Looks like this gets rid of the flakiness.

File: google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditorTest.java [hunk 1]
```diff
@@ -400,6 +400,7 @@ public void testDockerfileStartsDisabledAndWithModuleSetting() {
 
   @Override
   public void tearDown() throws Exception {
+    editor.getModulesWithFlexFacetComboBox().removeAllItems();
```
Comment (patflynn) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditorTest.java]: is this necessary if the editor is being disposed?

Comment (etanshaul) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/cloud/flexible/AppEngineFlexibleDeploymentEditorTest.java]: I'm worried that the editor isn't getting disposed because of this. 

I analyzed the heap dump and found paths to gc roots from this combobox. Its type is `JComboBox<Module>` which makes me suspect that it retains references to the modules causing the corresponding project to leak.

**Comment by etanshaul** [comment]
I may have spoke too soon. On reruning the builds I just got an error.

**Comment by etanshaul** [comment]
@patflynn I can't reproduce the failure now after about 5 builds. This, at a minimum, reduces the project leaks.
