### PR TITLE
Fix NPE when no GCP project is selected and user types in repository selector.

### LINKED ISSUE #2212: error report:  NPE in CSR
```
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryDialog.updateButtons(SetupCloudRepositoryDialog.java:141)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryDialog.access$200(SetupCloudRepositoryDialog.java:39)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryDialog$2.textChanged(SetupCloudRepositoryDialog.java:126)
	at com.intellij.ui.DocumentAdapter.removeUpdate(DocumentAdapter.java:32)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:259)
	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:622)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:590)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:666)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1717)
	at com.google.cloud.tools.intellij.csr.RepositoryRemotePanel.disableRemoteNameField(RepositoryRemotePanel.java:60)
	at com.google.cloud.tools.intellij.csr.RepositoryRemotePanel.update(RepositoryRemotePanel.java:46)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryDialog$1.textChanged(SetupCloudRepositoryDialog.java:114)
	at com.intellij.ui.DocumentAdapter.insertUpdate(DocumentAdapter.java:27)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at 
........
com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction.uploadProjectToGoogleCloud(SetupCloudRepositoryAction.java:144)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction.actionPerformed(SetupCloudRepositoryAction.java:126)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)


```

app.name.version
 GoLand
app.version.major
 2018
app.version.minor
 1.5
java.version
 1.8.0_152-release
java.vm.vendor
 JetBrains s.r.o
os.name
 Windows 10
plugin.version
 18.6.1

### PR DESCRIPTION
**Pull request by ivanporty**
Fixes #2212.

`updateButtons()` is called when user types in repository selector and that led to NPE when no GCP project was pre-selected.

### CODE REVIEW

File: google-cloud-repos/src/com/google/cloud/tools/intellij/csr/SetupCloudRepositoryDialog.java [hunk 1]
```diff
@@ -137,6 +137,13 @@ private void updateRepositorySelector(CloudProject cloudProject) {
 
   private void updateButtons() {
     CloudProject selectedProject = projectSelector.getSelectedProject();
+    if (selectedProject == null) {
+      setErrorText(
+          CloudReposMessageBundle.message("cloud.repository.selector.missing.project.error"));
+      setOKActionEnabled(false);
```
Comment (patflynn) [inline google-cloud-repos/src/com/google/cloud/tools/intellij/csr/SetupCloudRepositoryDialog.java]: screenshot?

Comment (ivanporty) [reply google-cloud-repos/src/com/google/cloud/tools/intellij/csr/SetupCloudRepositoryDialog.java]: repo-project-error

**Comment by patflynn** [comment]
could you disable the repo input widget until project is selected?  That
could be enough to make it clear what the user has to do..

**Comment by ivanporty** [comment]
I thought about that but was cautious to change familiar behavior - let's do that instead, having an enabled text field in this case does not make any sense indeed.

**Comment by ivanporty** [comment]
No project selected:
setup-repo-disabled

Project is selected:

setup-repo-enabled
