### PR TITLE
Fix errorprone compile warnings.

### LINKED ISSUE #1988: Fix errorprone warnings in CloudLibraryProjectStateTest.java
google-cloud-intellij/google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/apis/CloudLibraryProjectStateTest.java:119: warning: [CatchFail] Ignoring exceptions and calling fail() is unnecessary, and makes test output less useful
                        try {
                        ^
    (see http://errorprone.info/bugpattern/CatchFail)
google-cloud-intellij/google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/apis/CloudLibraryProjectStateTest.java:120: warning: [DefaultCharset] Implicit use of the platform default charset, which can result in e.g. non-ASCII characters being silently replaced with '?' in many environments
                          mavenProject.getFile().setBinaryContent("not a valid pom.xml".getBytes());
                                                                                                ^
    (see http://errorprone.info/bugpattern/DefaultCharset)
  Did you mean 'mavenProject.getFile().setBinaryContent("not a valid pom.xml".getBytes(UTF_8));' or 'mavenProject.getFile().setBinaryContent("not a valid pom.xml".getBytes(Charset.defaultCharset()));'?

### PR DESCRIPTION
**Pull request by ivanporty**
Fixes #1988.

### CODE REVIEW

File: google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/apis/CloudLibraryProjectStateTest.java [hunk 1]
```diff
@@ -117,9 +117,12 @@ public void getCloudLibraries_withMalformedPom_isEmpty() {
...
                       () -> {
                         try {
-                          mavenProject.getFile().setBinaryContent("not a valid pom.xml".getBytes());
+                          mavenProject
+                              .getFile()
+                              .setBinaryContent(
+                                  "not a valid pom.xml".getBytes(Charset.defaultCharset()));
                         } catch (IOException e) {
-                          fail();
+                          throw new AssertionError(e);
```
Comment (patflynn) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/apis/CloudLibraryProjectStateTest.java]: It'd be good to add a message to the assertion error just to emphasize what is failing about the test.  It'll also make it clear that AssertionError is thrown by the test code.

Comment (etanshaul) [reply google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/apis/CloudLibraryProjectStateTest.java]: btw, `fail` internally throws an `AssertionError`. So if this update silences the warning then its just because the analyzer isn't smart enough.

Comment (etanshaul) [reply google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/apis/CloudLibraryProjectStateTest.java]: oh nm. its about the stacktrace being lost. lgtm (after @patflynn comment)
