### PR TITLE
Fix for npe on findFirst with null facet

### LINKED ISSUE #1525: NullPointer from AppEngineUtil#findAppEngineStandardFacet
```
Description
null
Stack trace:
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:193)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:190)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.google.cloud.tools.intellij.appengine.util.AppEngineUtil.findAppEngineStandardFacet(AppEngineUtil.java:185)
	at com.google.cloud.tools.intellij.appengine.server.instance.AppEngineServerModel.checkConfiguration(AppEngineServerModel.java:134)
	at com.intellij.javaee.run.configuration.CommonStrategy.checkConfiguration(CommonStrategy.java:336)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.checkSettings(RunnerAndConfigurationSettingsImpl.java:442)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.checkSettings(RunnerAndConfigurationSettingsImpl.java:437)
	at com.intellij.execution.impl.RunManagerImpl.a(RunManagerImpl.java:1116)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:90)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception class name:
java.lang.NullPointerException
Exception message:
null
Throw file name:
Objects.java
Throw line number:
203
Throw class name:
java.util.Objects
Throw method name:
requireNonNull
Product Version:
2017.1.4
```

### PR DESCRIPTION
**Pull request by etanshaul**
Fixes #1525 

Fix for a few post-release reports we've seen. The problem is that findFirst() throws an NPE if the first element found in the stream is null, and the app engine standard facet could potentially be null.

To reproduce the error: open an ae standard project and then delete the standard facet. The checkConfiguration() method for the local run config (which is called periodically) will then try to load the standard facet (which is missing) and then throw an NPE.

After the fix, there is no error, and the run config shows up in an errored state as expected:

screen shot 2017-06-29 at 11 21 21 am

### CODE REVIEW

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/util/AppEngineUtil.java [hunk 1]
```diff
@@ -182,7 +183,9 @@ public void customize(JList list, Artifact value, int index, boolean selected,
     return ArtifactUtil.getModulesIncludedInArtifacts(Collections.singletonList(artifact), project)
         .stream()
         .map(AppEngineStandardFacet::getAppEngineFacetByModule)
-        .findFirst();
+        .map(Optional::ofNullable)
+        .findFirst()
+        .flatMap(Function.identity());
```
Comment (nkibler) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/util/AppEngineUtil.java]: What's the purpose of this line?

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/util/AppEngineUtil.java]: the flatMap? its to flatten out the Optional created by :186

`map(Optional::ofNullable)` will create create a stream of Optionals (replacing nulls with Optional.empty). findFirst will then return the first Optional (in our error scenario, it will be Optional.empty). But since findFirst itself wraps the result in an Optional, it will be: `Optional<Optional>`. So we need to flatten it out.

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/util/AppEngineUtil.java]: im trying to add some test coverage to this too.

Comment (nkibler) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/util/AppEngineUtil.java]: Oh forgot that .findFirst() wraps in an optional :)

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/util/AppEngineUtil.java]: cool. coverage for the npe added.

File: google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/util/AppEngineUtilTest.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+/** Tests for {@link AppEngineUtil}. */
+public class AppEngineUtilTest extends PlatformTestCase {
+
+  @Override
+  protected void setUp() throws Exception {
+    super.setUp();
+  }
+
+  public void testMissingAppEngineStandardFacet() {
```
Comment (nkibler) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/util/AppEngineUtilTest.java]: Can you add a case where this would be true too?

Comment (etanshaul) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/util/AppEngineUtilTest.java]: yea, should have mentioned I was working on that too. A little tricker so I first pushed the test to cover the exception.

**Comment by etanshaul** [comment]
@nkibler ok coverage for both cases now added
