### PR TITLE
Check if panel is a repository item panel before retrieving the selected repository

### LINKED ISSUE #1221: RepositorySelector ClassCastException
com.google.cloud.tools.intellij.resources.RepositorySelector$ProjectNotSelectedPanel cannot be cast to com.google.cloud.tools.intellij.resources.RepositorySelector$RepositoryPanel
java.lang.ClassCastException: com.google.cloud.tools.intellij.resources.RepositorySelector$ProjectNotSelectedPanel cannot be cast to com.google.cloud.tools.intellij.resources.RepositorySelector$RepositoryPanel
	at com.google.cloud.tools.intellij.resources.RepositorySelector.getSelectedRepository(RepositorySelector.java:94)
	at com.google.cloud.tools.intellij.vcs.SetupCloudRepositoryDialog$2.textChanged(SetupCloudRepositoryDialog.java:122)
	at com.intellij.ui.DocumentAdapter.insertUpdate(DocumentAdapter.java:27)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1328)
	at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)

### PR DESCRIPTION
**Pull request by etanshaul**
Fixes #1221, and possibly #1222 and #1223

### CODE REVIEW

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/RepositorySelector.java [hunk 1]
```diff
@@ -91,13 +91,15 @@ public String getSelectedRepository() {
...
     }
 
-    Enumeration repos = ((RepositoryPanel) panel).getRepositories().children();
-    while (repos.hasMoreElements()) {
-      TreeNode repo = (TreeNode) repos.nextElement();
-
-      if (repo instanceof RepositoryModelItem
-          && getText().equals(((RepositoryModelItem) repo).getRepositoryId())) {
-        return getText();
+    if (panel instanceof RepositoryPanel) {
```
Comment (joaoandremartins) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/RepositorySelector.java]: What else could panel be an instance of, in this case?

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/RepositorySelector.java]: as discussed offline, panel gets instantiated differently if repo's are found vs if they are not found. So in the case of typing an invalid repo, the panel will be an instance of the empty panel type.
