### PR TITLE
Catch java components missing exception and show message to the user

### LINKED ISSUE #876: Detect and warn the user if the java appengine SDK component is not installed

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #876 

image

Pending new release of the common lib

### CODE REVIEW

**Comment by etanshaul** [comment]
@patflynn @meltsufin

**Comment by patflynn** [comment]
Error text should ideally be highlighted somehow.  Maybe using red?

**Comment by etanshaul** [comment]
I don't see any way to have the error text highlighted. I'm using `RemoteOperationCallback#errorOccured` to print the message (and indicate failed deployment) which doesn't give any options for customizing the look of the text.

I can look into this more separately in a different PR.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineStandardDeployTask.java [hunk 1]
```diff
@@ -88,6 +89,10 @@ public void execute(ProcessStartListener startListener) {
           stagingDirectory,
           startListener,
           deploy(stagingDirectory, startListener));
+    } catch (AppEngineJavaComponentsNotInstalledException ex) {
+      deploy.getCallback().errorOccurred(
+          GctBundle.message("appengine.deployment.error.missing.java.components"));
+      logger.warn(ex);
```
Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineStandardDeployTask.java]: I can't seem to ever remember this, but doesn't 'warn' also generate an error report?

**Comment by patflynn** [comment]
LGTM assuming the log level thing is right.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineStandardDeployTask.java (hunk 1 above)
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineStandardDeployTask.java]: I'm almost positive it does not but I'll confirm since I usually forget too.

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineStandardDeployTask.java]: Confirmed - it does not generate an error report. Will merge when travis is done.
